services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:

  KimaiPlugin\KimaiQuickbooksBundle\:
    resource: "../../*"
    exclude: "../../{Resources,vendor}"

  KimaiPlugin\KimaiQuickbooksBundle\Configuration\KimaiQuickbooksConfiguration:
    arguments:
      $settings: "%kimai_quickbooks_settings%"
