services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:

  KimaiPlugin\KimaiQuickbooksBundle\:
    resource: "../../*"
    exclude: "../../{Resources,vendor}"

  KimaiPlugin\KimaiQuickbooksBundle\Controller\:
    resource: "../../Controller"
    tags: ["controller.service_arguments"]

  KimaiPlugin\KimaiQuickbooksBundle\Configuration\KimaiQuickbooksConfiguration:
    arguments:
      $settings: "%kimai_quickbooks_settings%"

  KimaiPlugin\KimaiQuickbooksBundle\Repository\QBCustomerRepository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ['KimaiPlugin\KimaiQuickbooksBundle\Entity\QBCustomer']

  KimaiPlugin\KimaiQuickbooksBundle\Repository\QBConnectionRepository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: ['KimaiPlugin\KimaiQuickbooksBundle\Entity\QBConnection']
